framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

    session:
        enabled: false

    serializer:
        enabled: true

    property_access:
        enabled: true

    validation:
        enabled: true
        enable_attributes: true
